### PR TITLE
Implement /staff command

### PR DESCRIPTION
**Pull request by Telesphoreo**
Customizable in config.yml
Tested and worked

### CODE REVIEW

**Comment by mgejay** [comment]
How about we make these string lists instead of strings.

**Comment by Telesphoreo** [comment]
What do you mean?

**Comment by Telesphoreo** [comment]
Sorry. Forgot to put the ConfigEntries in. GitHub being a bitch

**Comment by mgejay** [comment]
@PacksGamingHD Instead of making the ranks strings, make them a string list so it's easier to list a player, also instead of the rank name, I'd rather have

rank1: example
rank2: example2
etc

And then grab the rank1,2,3, etc so they can customize rank names.

**Pull request closed without merging**
